### ISSUE TITLE
@type should return a string or an array of strings

### ISSUE THREAD

**Issue by madsbuch** [rubensworks/jsonld-streaming-serializer.js#20]
When I use this library I get the problem that @type properties are emitted wrongly (it appears):

```
{
  "@id": "6lVCTSYTV3mhfr-P5mC3GA",
  "firstName": [
   {
    "@value": "Hans"
   }
  ],
  "lastName": [
   {
    "@value": "Pedersen"
   }
  ],
  "isMarriedTo": [
   {
    "@id": "ETENsNBwVxCDVKnov76F0w"
   }
  ],
  "@type": [
   {
    "@value": "Person"
   }
  ]
 }
```

Where type should be merely

```
  "@type": "Person" // or ["Person"]
```

I am constructing type triples as follows:

```
triple(
      namedNode(id),
      namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"),
      literal(class))
```

Great library btw! Really appreciate it!

**Comment by rubensworks** [comment]
Oops, `@type` should be `"@type": ["Person"]` there indeed.

**Comment by rubensworks** [comment]
Oh wait, things are actually working as intended.
The triple you are passing is in fact invalid (range of `rdf:type` is IRI (namedNode)).

You are executing
```
triple(
      namedNode(id),
      namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"),
      literal(class))
```
while you actually should be executing 
```
triple(
      namedNode(id),
      namedNode("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"),
      namedNode(class))
```

This library does not do any validation of the RDF triples.
