### ISSUE TITLE
Add support for json-ld version 1.1

### ISSUE THREAD

**Issue by gebsl** [rubensworks/jsonld-streaming-serializer.js#21]
Hello,

I would like to use this library for jsonld version 1.1 documents. json-ld brings support for `@import` within `@context`. The dependency `jsonld-context-parser` has already support for resolving `@import` statements, but only, if processing mode is set to 1.1.

The problem (in my opinion) is that `jsonld-context-parser`'s default value for processing mode is only set, if no object is passed to function `parse` (see: https://github.com/rubensworks/jsonld-context-parser.js/blob/c1abad92757586d1749e89959abec3a8cd9d54aa/lib/ContextParser.ts#L643).

However, this library already passes an object to the parsing function (see: https://github.com/rubensworks/jsonld-streaming-serializer.js/blob/e1f7d07b1958527aee08974a9c15af86eb2dd2d7/lib/JsonLdSerializer.ts#L37). I think that's why the default value for processing mode is not set on object `IParseOptions`.

Is this by design or should this be fixed? I'm happy to submit a PR once this is a confirmed bug.
If it is a bug, I think actually it should be fixed in `jsonld-context-parser`, so maybe this issue is not in the correct repo.

Thanks for the awesome work though!

**Comment by rubensworks** [comment]
There may be a problem there indeed. I think the problem even lies in jsonld-context-parser.js, where it should set the default processing mode to 1.1 if none has been set.

So if I'm correct, `processingMode` should default to `ContextParser.DEFAULT_PROCESSING_MODE` here: https://github.com/rubensworks/jsonld-context-parser.js/blob/c1abad92757586d1749e89959abec3a8cd9d54aa/lib/ContextParser.ts#L645-L653
And then the `options` argument of that method can probably be simplified a bit.

**Comment by gebsl** [comment]
Yep that was also my thought. I think the problem is that `jsonld-streaming-serializer` already passes an object which will just overwrite the default object that wants to set the default processing mode.

I think the easiest and nicest fix would be to just set the default mode in `jsonld-context-parser` a little different. Instead of setting the default within the signature of the function, it could be something like this:

```typescript
  /**
   * Parse a JSON-LD context in any form.
   * @param {JsonLdContext} context A context, URL to a context, or an array of contexts/URLs.
   * @param {IParseOptions} options Optional parsing options.
   * @return {Promise<JsonLdContextNormalized>} A promise resolving to the context.
   */
  public async parse(context: JsonLdContext, options: IParseOptions = {}): Promise<JsonLdContextNormalized> {
    const {
      baseIRI,
      parentContext: parentContextInitial,
      external,
      processingMode = ContextParser.DEFAULT_PROCESSING_MODE,
      normalizeLanguageTags,
      ignoreProtection,
      minimalProcessing,
    } = options;

    // and so on...
}
```
Though I am not 100% sure whether this is valid typescript or not.

**Comment by rubensworks** [comment]
Yep, something like that should do the trick!
The linter and unit tests should indicate what other places need changes.
(since `processingMode` will always be defined because of this change, the falsy checks for it won't be needed anymore)

Setting the default `processingMode` like that won't work though, so we'll probably need something like this:
```
    const {
      baseIRI,
      parentContext: parentContextInitial,
      external,
      processingMode,
      normalizeLanguageTags,
      ignoreProtection,
      minimalProcessing,
    } = options;
    if (!processingMode)
      processingMode = ContextParser.DEFAULT_PROCESSING_MODE
```

**Comment by gebsl** [comment]
Yeah that looks neat! 
Shall I submit a PR for this?

**Comment by rubensworks** [comment]
Yes please :-)
